### ISSUE TITLE
Is serial TX nature of the API intentional?

### ISSUE THREAD

**Issue by pac-work** [vsf-tv/gccg-api#22]
The API callbacks have no way of identifying the specific request which caused the callback (only the whole connection). This means that all the requests belonging to one connection have to be serialized (for example the TX part cannot submit a data for transport before the previous submission succeeds or times out). Depending on a specific transport layer this may or may not be limiting.

**Comment by jmailhot** [comment]
agree it would be reasonable to add a reference that gets returned in the callback.

**Comment by mhhen** [comment]
The following parameter will be added to the GccgTxPayload API:

```
 * @param user_cb_param_ptr User defined callback parameter. This value is set as part of the GccgTxCbData data
 *                          whenever the tx_cb_ptr callback function specified in the GccgTxConnectionCreate() API
 *                          is invoked. The value is not modified by the SDK.
```

The value specified will be available in **GccgTxCbData** when the **GccgTxCallback** API is invoked.

**Comment by pac-work** [comment]
Thanks for including this, it may simplify the internal workings of the implementations.
