### ISSUE TITLE
Inconsistencies and referencing in the JSON and the .h file

### ISSUE THREAD

**Issue by pac-work** [vsf-tv/gccg-api#23]
- Naming inside the JSON is ambiguous at places (firstField vs. evenField for video vs. anc.)
- The code still refers to the CDI at some places (AWS CDI-SDK, CdiAvmTxCallback)

**Comment by jmailhot** [comment]
the naming of the fields is indeed fraught with peril.  we crossed this bridge in 2110-20 and defined it a specific way, probably best here to follow that.

**Comment by mhhen** [comment]
Will change both references to something like:

```
            "field": 0,          ## Zero or one. For interlaced, zero= first field, one= second field. ##
                                 ## For progressive, shall be set to zero, except in the case of progressive ##
                                 ## segmented frame data where it indicates the segment. ##
```

**Comment by pac-work** [comment]
Thanks, great!
