### ISSUE TITLE
Zero copy not always possible through the API

### ISSUE THREAD

**Issue by pac-work** [vsf-tv/gccg-api#25]
- For RX zero copy, one would need to supply a buffer to receive into (may not always be possible depending on the transport layer?).
- For TX zero copy, the API would have to provide malloc function.

**Comment by jmailhot** [comment]
The key question here is whether the receive buffer is "owned" by the implementation (and a reference provided to the application) or the other way around.  since the buffers might have very different requirements based on the underlying implementation, it seems best if the implementation creates/manages/owns them, and provides pointers up into the application.

**Comment by mhhen** [comment]
Yes, that is correct.

**Comment by pac-work** [comment]
Thanks for the explanation, I would personally choose a different type for the return value, just to signify it's intended use, but this works as well. Following code illustrates what I mean:
```
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

void current_alloc_function(uint64_t tx_buffer_size_bytes, void* ret_tx_buffer_ptr) {
    void* buffer_addr = malloc(tx_buffer_size_bytes);
    memcpy(ret_tx_buffer_ptr, &buffer_addr, sizeof(void*));
}

void alternative_alloc_function(uint64_t tx_buffer_size_bytes, void** ret_tx_buffer_ptr) {
    *ret_tx_buffer_ptr = malloc(tx_buffer_size_bytes);
}

int main()
{
    uint64_t my_buffer_size = 256;
    void* my_buffer;
    current_alloc_function(my_buffer_size, &my_buffer);
    printf("allocated buffer start: %p\n", my_buffer);
    alternative_alloc_function(my_buffer_size, &my_buffer);
    printf("allocated buffer start: %p\n", my_buffer);
    return 0;
}
```

Also, if there are some alignment requirements, returning one big buffer may require a deper knowledge of the actual implementation, but I guess each implementation with such a requirements can document them.
