### ISSUE TITLE
A user pointer in GccgSglEntry 

### ISSUE THREAD

**Issue by kierank** [vsf-tv/gccg-api#3]
A user pointer would be quite nice so we can map the address back to the user's object without doing CONTAINER_OF or other tricks.

**Comment by mhhen** [comment]
Adding this to `GccSglEntry` and `GccgSgList` structures:

```
    /// @brief User defined parameter. This value is not modified by the API.
    void* user_param_ptr;

```

**Comment by mhhen** [comment]
Addressed by: https://github.com/vsf-tv/gccg-api/pull/11
